### ISSUE TITLE
Flutter lots of issues

### ISSUE THREAD

**Issue by barisertemli** [creativecreatorormaybenot/clock#2]
I am so new in programming but I don't get it, why I am getting things like that ? I can't even run the preset flutter in emulator. I am too bored from that...

I tried to write **`flutter create .`**  to console. And I didn't watch any lesson videos from anywhere because I just wanted to see the preset works on emulator. But I couldn't see that... :/

![help](https://user-images.githubusercontent.com/48600314/76026876-ab9d9b80-5f40-11ea-8d16-bf9bc81647e0.png)

**Comment by creativecreatorormaybenot** [comment]
If you want to run the clock, make sure to `cd clock`, then `flutter create .`, and then `flutter run`.

Let me know if this works.

**Comment by barisertemli** [comment]
> If you want to run the clock, make sure to `cd clock`, then `flutter create .`, and then `flutter run`.
> 
> Let me know if this works.

When i write **`cd clock`** it can't find the path... Bro what am I doing wrong...

**Comment by barisertemli** [comment]
I just changed the location of project and everything worked... Still can't believe.
