### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by asmith20002** [creativecreatorormaybenot/clock#3]
Hello,

Thank you for this repo. Decided to test it locally on my windows. There are issues.

For example:
[#File](https://github.com/creativecreatorormaybenot/clock/blob/master/canvas_clock/lib/components/climate/weather.dart#L37)

```
The private name '_tickerModeNotifier', defined by 'TickerProviderStateMixin', conflicts with the same name defined by 'SingleTickerProviderStateMixin'.
```

Is there any chance you could update this repo?

**Comment by creativecreatorormaybenot** [comment]
Hi - as this repo is only a snapshot of my submission to the [Flutter Clock challenge](https://docs.flutter.dev/clock#:~:text=Flutter%20Clock%20is%20a%20skills,and%20innovative%20clock%20face%20application.) from 2020, I will leave the code as is. If you want to make it work, you can use a version of Flutter from that time.
